#! /bin/bash
entropy=0
length=0
show_dice=0
while getopts 'rl:' opt; do
	case $opt in
		l) length=$OPTARG;;
		r) show_dice=1;;
		\?) echo 'Invalid' $OPTARG;;
		:) echo "Option $OPTARG requires an argument.";;
	esac
done
for ((count=0; $count < $length; count+=1)); do
	diearr=()
	for ((die=0; $die < 5; die+=1)); do
		number=0
		while :; do
			number=$(head -c 1 /dev/random | hexdump -e '"%u"')
			[[ "$value" -gt 251 ]] || break
		done
		number=$(($number % 6 + 1))
		diearr+=$number
	done
	if [ $show_dice -eq 1 ]; then
		awk -F'\t' "/$diearr/ { print; }" wordlist
	else
		awk -F'\t' "/$diearr/ { print "'$2'"; }" wordlist
	fi
done
